# 服务配置
server:
  port: 9001
# spring配置
spring:
  # 1、应用配置
  application:
    name: ihrm-company
  #2、数据库连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm01?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #3、JPA配置
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
